package mnj.model.service;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 25 16:47:15 BDT 2018
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for OrderVO1.
     * @return OrderVO1
     */
    public ViewObjectImpl getOrderVO1() {
        return (ViewObjectImpl)findViewObject("OrderVO1");
    }


    /**
     * Container's getter for selectORG1.
     * @return selectORG1
     */
    public ViewObjectImpl getselectORG1() {
        return (ViewObjectImpl)findViewObject("selectORG1");
    }

    /**
     * Container's getter for ORGLov1.
     * @return ORGLov1
     */
    public ViewObjectImpl getORGLov1() {
        return (ViewObjectImpl)findViewObject("ORGLov1");
    }

    /**
     * Container's getter for searchVO1.
     * @return searchVO1
     */
    public ViewObjectImpl getsearchVO1() {
        return (ViewObjectImpl)findViewObject("searchVO1");
    }

    /**
     * Container's getter for SeasonLOV1.
     * @return SeasonLOV1
     */
    public ViewObjectImpl getSeasonLOV1() {
        return (ViewObjectImpl)findViewObject("SeasonLOV1");
    }

    /**
     * Container's getter for BuyerLOV1.
     * @return BuyerLOV1
     */
    public ViewObjectImpl getBuyerLOV1() {
        return (ViewObjectImpl)findViewObject("BuyerLOV1");
    }

    /**
     * Container's getter for OrderRecapVO1.
     * @return OrderRecapVO1
     */
    public ViewObjectImpl getOrderRecapVO1() {
        return (ViewObjectImpl)findViewObject("OrderRecapVO1");
    }

    /**
     * Container's getter for OrderRecapSummary1.
     * @return OrderRecapSummary1
     */
    public ViewObjectImpl getOrderRecapSummary1() {
        return (ViewObjectImpl)findViewObject("OrderRecapSummary1");
    }

    /**
     * Container's getter for order_recap_new_view1.
     * @return order_recap_new_view1
     */
    public ViewObjectImpl getorder_recap_new_view1() {
        return (ViewObjectImpl)findViewObject("order_recap_new_view1");
    }
}
